name: test
on:
  push:
    branches:
      - main
      - feat/prisma

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: 查看pnpm版本
        run: pnpm --version

      - name: 安装依赖
        run: pnpm install

      - name: 迁移数据库
        run: pnpm exec prisma migrate dev --name init

      - name: 生成 Prisma Client
        run: pnpm exec prisma generate

      - name: 运行测试
        run: pnpm run test